
package ts3.webapi.client.clientservice.wcf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ClientService", targetNamespace = "Wcf.ClientService.Client.WebAPI.TS3", wsdlLocation = "https://api-b2b.4tochki.ru/WCF/ClientService.svc?wsdl")
public class ClientService_Service
    extends Service
{

    private static final URL CLIENTSERVICE_WSDL_LOCATION;
    private static final WebServiceException CLIENTSERVICE_EXCEPTION;
    private static final QName CLIENTSERVICE_QNAME = new QName("Wcf.ClientService.Client.WebAPI.TS3", "ClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api-b2b.4tochki.ru/WCF/ClientService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSERVICE_WSDL_LOCATION = url;
        CLIENTSERVICE_EXCEPTION = e;
    }

    public ClientService_Service() {
        super(__getWsdlLocation(), CLIENTSERVICE_QNAME);
    }

    public ClientService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSERVICE_QNAME, features);
    }

    public ClientService_Service(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSERVICE_QNAME);
    }

    public ClientService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSERVICE_QNAME, features);
    }

    public ClientService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientService
     */
    @WebEndpoint(name = "BasicHttpBinding_ClientService")
    public ClientService getBasicHttpBindingClientService() {
        return super.getPort(new QName("Wcf.ClientService.Client.WebAPI.TS3", "BasicHttpBinding_ClientService"), ClientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientService
     */
    @WebEndpoint(name = "BasicHttpBinding_ClientService")
    public ClientService getBasicHttpBindingClientService(WebServiceFeature... features) {
        return super.getPort(new QName("Wcf.ClientService.Client.WebAPI.TS3", "BasicHttpBinding_ClientService"), ClientService.class, features);
    }

    /**
     * 
     * @return
     *     returns ClientService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ClientService")
    public ClientService getBasicHttpsBindingClientService() {
        return super.getPort(new QName("Wcf.ClientService.Client.WebAPI.TS3", "BasicHttpsBinding_ClientService"), ClientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientService
     */
    @WebEndpoint(name = "BasicHttpsBinding_ClientService")
    public ClientService getBasicHttpsBindingClientService(WebServiceFeature... features) {
        return super.getPort(new QName("Wcf.ClientService.Client.WebAPI.TS3", "BasicHttpsBinding_ClientService"), ClientService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSERVICE_EXCEPTION!= null) {
            throw CLIENTSERVICE_EXCEPTION;
        }
        return CLIENTSERVICE_WSDL_LOCATION;
    }

}
